Failure # 1 (occurred at 2021-02-27_19-04-53)
Traceback (most recent call last):
  File "/home/schwaiger_franziska11861/.local/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 586, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/schwaiger_franziska11861/.local/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 609, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/schwaiger_franziska11861/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/schwaiger_franziska11861/.local/lib/python3.8/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): [36mray::ImplicitFunc.train_buffered()[39m (pid=24311, ip=10.128.0.5)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/home/schwaiger_franziska11861/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 167, in train_buffered
    result = self.train()
  File "/home/schwaiger_franziska11861/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 226, in train
    result = self.step()
  File "/home/schwaiger_franziska11861/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 366, in step
    self._report_thread_runner_error(block=True)
  File "/home/schwaiger_franziska11861/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 512, in _report_thread_runner_error
    raise TuneError(
ray.tune.error.TuneError: Trial raised an exception. Traceback:
[36mray::ImplicitFunc.train_buffered()[39m (pid=24311, ip=10.128.0.5)
  File "/home/schwaiger_franziska11861/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/home/schwaiger_franziska11861/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 315, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "/home/schwaiger_franziska11861/.local/lib/python3.8/site-packages/ray/tune/function_runner.py", line 576, in _trainable_func
    output = fn()
  File "/home/schwaiger_franziska11861/ADLR/src/train.py", line 85, in train
    train_INN(model=model, config=config, dataloader=train_dataloader, device=device, hyperparam_tuning=hyperparam_tuning)
  File "/home/schwaiger_franziska11861/ADLR/src/train_loader.py", line 281, in train_INN
    loss_backward.backward()
  File "/home/schwaiger_franziska11861/.local/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/schwaiger_franziska11861/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Function 'ReciprocalBackward' returned nan values in its 0th output.

